name: docker build and push

on:
  push:
    paths-ignore:
    - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - 
      name: 'Build Inventory Image'
      run: |
        docker build . --tag ghcr.io/biosvos/markadr:latest
        docker push ghcr.io/biosvos/markadr
