name: docker build and push

on:
  push:
    paths-ignore:
    - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.1.1
      with:
        push: true
        tags: biosvos/markadr:latest
